services:
  - type: web
    name: commerce
    env: python
    pythonVersion: 3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn commerce.wsgi:application --bind 0.0.0.0:$PORT"
