gunicorn commerce.wsgi:application --bind 0.0.0.0:10000 

services:
  - type: web
    name: commerce
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn commerce.wsgi:application --bind 0.0.0.0:10000 "
    plan: free